// src/components/quiz/registry/componentRegistry.ts
import { ComponentType } from "react";
import { ZodSchema } from "zod";
import {
  Type,
  Heading,
  Image,
  Video,
  ListChecks,
  User,
  Mail,
  Phone,
  Calendar,
  Sliders,
  Sparkles,
  MousePointerClick,
  Layers,
  SquareCheck,
  Award,
  HelpCircle,
  LucideIcon,
  CreditCard,
  FileText
} from "lucide-react";

import { QuizComponentType, QuizComponentCategory } from "@/types/quiz";
import {
  TextComponentSchema,
  ImageComponentSchema,
  VideoComponentSchema,
  ButtonComponentSchema,
  OptionsComponentSchema,
  InputFieldSchema,
  SliderFieldSchema,
  ResultCardSchema,
} from "@/schemas/quiz";

export interface ComponentDefinition<T = any> {
  type: QuizComponentType;
  label: string;
  description: string;
  category: QuizComponentCategory;
  icon: LucideIcon;
  defaultConfig: T;
  schema: ZodSchema<T>;
  supportsConditions: boolean;
  supportsResponsive: boolean;
  supportsDataBinding: boolean;
  migrationVersion: number;
}

export const COMPONENT_REGISTRY: Record<QuizComponentType, ComponentDefinition> = {
  // ─── Content ──────────────────────────────────────────────────────────────
  rich_text: {
    type: "rich_text",
    label: "Texto",
    description: "Títulos, parágrafos e textos ricos formatados.",
    category: "content",
    icon: Type,
    defaultConfig: {
      content: "<p>Digite seu texto...</p>",
      defaultBlockStyle: "paragraph",
      defaultTextSize: "normal",
      alignment: "center",
      width: "100%",
      showOnMobile: true,
      showOnTablet: true,
      showOnDesktop: true,
    },
    schema: TextComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  text: {
    type: "text",
    label: "Texto",
    description: "Títulos, parágrafos e textos ricos formatados.",
    category: "content",
    icon: Type,
    defaultConfig: {
      content: "<p>Digite seu texto...</p>",
      alignment: "center",
    },
    schema: TextComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  heading: {
    type: "heading",
    label: "Texto",
    description: "Títulos, parágrafos e textos ricos formatados.",
    category: "content",
    icon: Type,
    defaultConfig: {
      content: "<h2>Descubra o Perfil Ideal</h2>",
      alignment: "center",
    },
    schema: TextComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  image: {
    type: "image",
    label: "Imagem / Banner",
    description: "Upload de foto com proporção, legenda e link.",
    category: "content",
    icon: Image,
    defaultConfig: {
      url: "",
      alt: "Imagem descritiva",
      width: "100%",
      maxWidth: "100%",
      aspectRatio: "auto",
      objectFit: "cover",
      alignment: "center",
    },
    schema: ImageComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  video: {
    type: "video",
    label: "Vídeo Embed",
    description: "Vídeos do YouTube, Vimeo ou Wistia.",
    category: "content",
    icon: Video,
    defaultConfig: {
      url: "",
      provider: "youtube",
      autoPlay: false,
      controls: true,
      aspectRatio: "16:9",
    },
    schema: VideoComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  logo: {
    type: "logo",
    label: "Logotipo Central",
    description: "Marca visual da empresa ou campanha.",
    category: "content",
    icon: Sparkles,
    defaultConfig: {
      url: "",
      alt: "Logotipo",
      width: "140px",
      alignment: "center",
    },
    schema: ImageComponentSchema,
    supportsConditions: false,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },

  // ─── Questions ────────────────────────────────────────────────────────────
  options: {
    type: "options",
    label: "Quiz / Múltipla Escolha",
    description: "Perguntas de escolha única ou múltipla com opções customizadas.",
    category: "question",
    icon: ListChecks,
    defaultConfig: {
      question: "Qual é o seu objetivo principal?",
      required: true,
      multiple: false,
      autoAdvance: true,
      displayStyle: "list",
      options: [
        { id: "opt-1", text: "Aumentar faturamento rapidamente", value: "A", points: 10, destination: null },
        { id: "opt-2", text: "Otimizar processos e automação", value: "B", points: 5, destination: null },
      ],
    },
    schema: OptionsComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  cards_choice: {
    type: "cards_choice",
    label: "Escolha em Cards / Imagens",
    description: "Perguntas visuais com cards contendo fotos ou ícones.",
    category: "question",
    icon: CreditCard,
    defaultConfig: {
      question: "Qual estilo mais combina com você?",
      required: true,
      multiple: false,
      autoAdvance: true,
      displayStyle: "grid",
      columns: 2,
      options: [
        { id: "opt-c1", text: "Opção Premium", value: "P1", points: 10, image: null },
        { id: "opt-c2", text: "Opção Padrão", value: "P2", points: 5, image: null },
      ],
    },
    schema: OptionsComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  rating_stars: {
    type: "rating_stars",
    label: "Avaliação (Estrelas)",
    description: "Classificação de 1 a 5 estrelas.",
    category: "question",
    icon: Award,
    defaultConfig: {
      question: "Como você avalia nossa experiência?",
      required: true,
      variableName: "rating_stars",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  nps: {
    type: "nps",
    label: "Pesquisa NPS (0-10)",
    description: "Medição de satisfação NPS de 0 a 10.",
    category: "question",
    icon: Award,
    defaultConfig: {
      question: "De 0 a 10, qual a chance de recomendar a Qualify?",
      required: true,
      variableName: "nps_score",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  scale_slider: {
    type: "scale_slider",
    label: "Escala / Slider Numérico",
    description: "Barra deslizante para pesos, medidas ou valores.",
    category: "question",
    icon: Sliders,
    defaultConfig: {
      label: "Selecione a quantidade desejada:",
      required: false,
      unit: "unidades",
      defaultValue: 50,
      min: 0,
      max: 100,
      step: 1,
      variableName: "slider_val",
    },
    schema: SliderFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },

  // ─── Capture ──────────────────────────────────────────────────────────────
  field_name: {
    type: "field_name",
    label: "Nome Completo",
    description: "Captura do nome do lead para CRM.",
    category: "capture",
    icon: User,
    defaultConfig: {
      label: "Seu Nome Completo",
      placeholder: "Digite seu nome...",
      required: true,
      variableName: "name",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_email: {
    type: "field_email",
    label: "E-mail",
    description: "Campo com validação estrita de formato de e-mail.",
    category: "capture",
    icon: Mail,
    defaultConfig: {
      label: "Seu E-mail",
      placeholder: "nome@exemplo.com.br",
      required: true,
      variableName: "email",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_phone: {
    type: "field_phone",
    label: "Celular / WhatsApp",
    description: "Campo de telefone com máscara automática (DD9XXXX-XXXX).",
    category: "capture",
    icon: Phone,
    defaultConfig: {
      label: "WhatsApp / Celular com DDD",
      placeholder: "(11) 99999-9999",
      required: true,
      variableName: "phone",
      mask: "(99) 99999-9999",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_cpf: {
    type: "field_cpf",
    label: "CPF",
    description: "Campo de documento CPF com máscara.",
    category: "capture",
    icon: FileText,
    defaultConfig: {
      label: "CPF",
      placeholder: "000.000.000-00",
      required: false,
      variableName: "cpf",
      mask: "999.999.999-99",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_cnpj: {
    type: "field_cnpj",
    label: "CNPJ",
    description: "Campo de documento empresarial com máscara.",
    category: "capture",
    icon: FileText,
    defaultConfig: {
      label: "CNPJ da Empresa",
      placeholder: "00.000.000/0001-00",
      required: false,
      variableName: "cnpj",
      mask: "99.999.999/9999-99",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_number: {
    type: "field_number",
    label: "Campo Numérico",
    description: "Entrada restrita para números.",
    category: "capture",
    icon: Sliders,
    defaultConfig: {
      label: "Quantidade",
      placeholder: "0",
      required: false,
      variableName: "number_val",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_textarea: {
    type: "field_textarea",
    label: "Texto Longo / Mensagem",
    description: "Caixa de texto multilinhas.",
    category: "capture",
    icon: Type,
    defaultConfig: {
      label: "Observações / Detalhes",
      placeholder: "Escreva aqui os detalhes...",
      required: false,
      variableName: "message",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_date: {
    type: "field_date",
    label: "Data",
    description: "Seletor de data.",
    category: "capture",
    icon: Calendar,
    defaultConfig: {
      label: "Data Desejada",
      required: false,
      variableName: "selected_date",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_select: {
    type: "field_select",
    label: "Lista Dropdown (Select)",
    description: "Caixa de seleção suspensa.",
    category: "capture",
    icon: ListChecks,
    defaultConfig: {
      label: "Selecione uma opção",
      required: false,
      variableName: "selected_dropdown",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_checkbox: {
    type: "field_checkbox",
    label: "Checkbox de Consentimento",
    description: "Caixa de marcação para termos e privacidade.",
    category: "capture",
    icon: SquareCheck,
    defaultConfig: {
      label: "Concordo com os termos e política de privacidade.",
      required: true,
      variableName: "consent",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_height: {
    type: "field_height",
    label: "Altura (cm)",
    description: "Slider de altura em centímetros.",
    category: "capture",
    icon: Sliders,
    defaultConfig: {
      label: "Sua Altura",
      unit: "cm",
      defaultValue: 175,
      min: 100,
      max: 230,
      variableName: "height",
    },
    schema: SliderFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_weight: {
    type: "field_weight",
    label: "Peso (kg)",
    description: "Slider de peso em quilos.",
    category: "capture",
    icon: Sliders,
    defaultConfig: {
      label: "Seu Peso",
      unit: "kg",
      defaultValue: 70,
      min: 30,
      max: 250,
      variableName: "weight",
    },
    schema: SliderFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  field_custom: {
    type: "field_custom",
    label: "Campo Personalizado",
    description: "Campo customizado integrado aos campos de CRM.",
    category: "capture",
    icon: HelpCircle,
    defaultConfig: {
      label: "Informação Adicional",
      placeholder: "Digite aqui...",
      required: false,
      variableName: "custom_field",
    },
    schema: InputFieldSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },

  // ─── Conversion ───────────────────────────────────────────────────────────
  button: {
    type: "button",
    label: "Botão Principal (CTA)",
    description: "Botão de ação com animação e efeitos.",
    category: "conversion",
    icon: MousePointerClick,
    defaultConfig: {
      text: "Continuar para Próxima Etapa",
      style: "primary",
      size: "md",
      width: "100%",
      alignment: "center",
      animated: true,
      actionType: "next_step",
    },
    schema: ButtonComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  cta_whatsapp: {
    type: "cta_whatsapp",
    label: "Botão WhatsApp Direct",
    description: "Abre conversa direta no WhatsApp preenchendo a mensagem.",
    category: "conversion",
    icon: Phone,
    defaultConfig: {
      text: "Falar Agora no WhatsApp",
      style: "primary",
      size: "lg",
      width: "100%",
      alignment: "center",
      animated: true,
      actionType: "whatsapp",
    },
    schema: ButtonComponentSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },

  // ─── Structure ────────────────────────────────────────────────────────────
  container: {
    type: "container",
    label: "Bloco Contêiner",
    description: "Bloco de agrupamento de elementos.",
    category: "structure",
    icon: Layers,
    defaultConfig: {},
    schema: TextComponentSchema as any,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  card: {
    type: "card",
    label: "Card Estilizado",
    description: "Caixa destacada com bordas e sombra.",
    category: "structure",
    icon: CreditCard,
    defaultConfig: {},
    schema: TextComponentSchema as any,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  spacer: {
    type: "spacer",
    label: "Espaçador Vertical",
    description: "Espaço em branco para respirar o layout.",
    category: "structure",
    icon: Layers,
    defaultConfig: { height: 24 },
    schema: TextComponentSchema as any,
    supportsConditions: false,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
  divider: {
    type: "divider",
    label: "Linha Divisória",
    description: "Separador sutil entre seções.",
    category: "structure",
    icon: Layers,
    defaultConfig: { style: "solid" },
    schema: TextComponentSchema as any,
    supportsConditions: false,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },

  // ─── Results ──────────────────────────────────────────────────────────────
  result_score: {
    type: "result_score",
    label: "Card de Pontuação Final",
    description: "Exibe o resultado com base nos pontos acumulados.",
    category: "result",
    icon: Award,
    defaultConfig: {
      title: "Parabéns pelo Diagnóstico!",
      description: "Você atingiu um perfil de Alta Qualificação.",
      showScore: true,
      badgeText: "Aprovado",
      ctaText: "Receber Relatório Completo via WhatsApp",
      ctaAction: "whatsapp",
    },
    schema: ResultCardSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  result_status: {
    type: "result_status",
    label: "Resultado de Status (Sucesso/Erro)",
    description: "Apresenta confirmação visual de conclusão.",
    category: "result",
    icon: Award,
    defaultConfig: {
      title: "Respostas Enviadas com Sucesso!",
      description: "Entraremos em contato em breve.",
      showScore: false,
      badgeText: "Concluído",
      ctaText: "Voltar ao Início",
      ctaAction: "redirect",
    },
    schema: ResultCardSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: true,
    migrationVersion: 1,
  },
  result_redirect: {
    type: "result_redirect",
    label: "Redirecionamento Automático",
    description: "Redireciona o visitante para uma URL externa pós-resposta.",
    category: "result",
    icon: MousePointerClick,
    defaultConfig: {
      title: "Redirecionando...",
      description: "Você será direcionado em alguns instantes.",
    },
    schema: ResultCardSchema,
    supportsConditions: true,
    supportsResponsive: true,
    supportsDataBinding: false,
    migrationVersion: 1,
  },
};

export const getComponentDef = (type: QuizComponentType): ComponentDefinition => {
  return COMPONENT_REGISTRY[type] || COMPONENT_REGISTRY.text;
};
